.lint: &lint
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apk add --no-cache --update git
    - bundle install --clean --deployment --jobs=2 --without default development production test
  image: ruby:alpine
  stage: lint

.test: &test
  script:
    - bundle install --clean --deployment --jobs=$(nproc) --without development lint production
    - bin/rake
  stage: test

.use_jruby: &use_jruby
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apt-get -qq update
    - apt-get -qq install git
  image: jruby:9.1

.use_mri: &use_mri
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version

.use_rails_4_0_x: &use_rails_4_0_x
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-4.0.x

.use_rails_4_1_x: &use_rails_4_1_x
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-4.1.x

.use_rails_4_2_x: &use_rails_4_2_x
  variables:
    BUNDLE_GEMFILE: Gemfile

.use_rails_5_0_x: &use_rails_5_0_x
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-5.0.x

cache:
  paths:
    - vendor/bundle

lint:brakeman:
  <<: *lint
  script:
    - bin/brakeman

lint:bundler:audit:
  <<: *lint
  script:
    - bin/bundle-audit check --update --verbose

lint:rubocop:
  <<: *lint
  script:
    - bin/rubocop

stages:
  - lint
  - test


test:rails-4.0.x:jruby:9.1:
  <<: *test
  <<: *use_jruby
  <<: *use_rails_4_0_x

test:rails-4.0.x:mri:2.1:
  <<: *test
  <<: *use_mri
  <<: *use_rails_4_0_x
  image: ruby:2.1

test:rails-4.0.x:mri:2.2:
  <<: *test
  <<: *use_mri
  <<: *use_rails_4_0_x
  image: ruby:2.2

test:rails-4.0.x:mri:2.3:
  <<: *test
  <<: *use_mri
  <<: *use_rails_4_0_x
  image: ruby:2.3

test:rails-4.1.x:jruby:9.1:
  <<: *test
  <<: *use_jruby
  <<: *use_rails_4_1_x

test:rails-4.1.x:mri:2.1:
  <<: *test
  <<: *use_mri
  <<: *use_rails_4_1_x
  image: ruby:2.1

test:rails-4.1.x:mri:2.2:
  <<: *test
  <<: *use_mri
  <<: *use_rails_4_1_x
  image: ruby:2.2

test:rails-4.1.x:mri:2.3:
  <<: *test
  <<: *use_mri
  <<: *use_rails_4_1_x
  image: ruby:2.3

test:rails-4.2.x:jruby:9.1:
  <<: *test
  <<: *use_jruby
  <<: *use_rails_4_2_x

test:rails-4.2.x:mri:2.1:
  <<: *test
  <<: *use_mri
  <<: *use_rails_4_2_x
  image: ruby:2.1

test:rails-4.2.x:mri:2.2:
  <<: *test
  <<: *use_mri
  <<: *use_rails_4_2_x
  image: ruby:2.2

test:rails-4.2.x:mri:2.3:
  <<: *test
  <<: *use_mri
  <<: *use_rails_4_2_x
  image: ruby:2.3

test:rails-5.0.x:jruby:9.1:
  allow_failure: true
  <<: *test
  <<: *use_jruby
  <<: *use_rails_5_0_x

test:rails-5.0.x:mri:2.2:
  <<: *test
  <<: *use_mri
  <<: *use_rails_5_0_x
  image: ruby:2.2

test:rails-5.0.x:mri:2.3:
  <<: *test
  <<: *use_mri
  <<: *use_rails_5_0_x
  image: ruby:2.3

variables:
  JRUBY_OPTS: --debug
  LC_ALL: C.UTF-8
  RAILS_ENV: test
