addons:
  code_climate:
    repo_token: 8a344833c6693733b163f09a5243fa12dd7be0b69f0358b146c64dd4becabc60
after_script:
  - bin/codeclimate-test-reporter
bundler_args: --clean --deployment --jobs=$(nproc) --without development production
cache: bundler
dist: trusty
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
jdk:
  - openjdk8
language: ruby
matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.rails-4.0.x 
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.rails-4.1.x 
  allow_failures:
    - rvm: rbx-3
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.9.0
  - rbx-3
sudo: required
