after_success:
  - bin/codeclimate-test-reporter
bundler_args: --clean --deployment --jobs=$(nproc) --without development production
cache: bundler
dist: trusty
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-5.0.x
jdk:
  - openjdk7
language: ruby
matrix:
  exclude:
    - rvm: 2.1.9
      gemfile: gemfiles/Gemfile.rails-5.0.x 
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.rails-4.0.x 
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.rails-4.1.x 
  allow_failures:
    - rvm: rbx-3
    - rvm: jruby-9.1.6.0
      gemfile: gemfiles/Gemfile.rails-5.0.x
rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - jruby-9.1.6.0
  - rbx-3
sudo: required
