addons:
  code_climate:
    repo_token: 8a344833c6693733b163f09a5243fa12dd7be0b69f0358b146c64dd4becabc60
before_script:
  - bin/brakeman
bundler_args: --clean --deployment --jobs=3 --retry=3 --without development production
cache: bundler
dist: trusty
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-5.0.x
jdk:
  - openjdk7
language: ruby
matrix:
  include:
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-5.0.x 
      jdk:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.rails-5.0.x 
    - rvm: 2.4.0-preview2
      gemfile: gemfiles/Gemfile.rails-4.0.x 
    - rvm: 2.4.0-preview2
      gemfile: gemfiles/Gemfile.rails-4.1.x 
  allow_failures:
    - rvm: rbx-3
    - rvm: 2.4.0-preview2
      gemfile: Gemfile
    - rvm: jruby-9.1.5.0
      gemfile: gemfiles/Gemfile.rails-5.0.x
rvm:
  - 2.1
  - 2.2.2
  - 2.3.1
  - 2.4.0-preview2
  - jruby-9.1.5.0
  - rbx-3
sudo: required
