addons:
  code_climate:
    repo_token: 8a344833c6693733b163f09a5243fa12dd7be0b69f0358b146c64dd4becabc60
before_script:
  - bin/brakeman
bundler_args: --clean --deployment --jobs=3 --retry=3 --without development production
cache: bundler
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.2.x
jdk:
  - openjdk7
language: ruby
matrix:
  allow_failures:
    - rvm: rbx-3.24
    - rvm: ruby-head
  exclude:
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: 2.2
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: 2.3.0
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: jruby-9.0.5.0
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: rbx-3.19
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: ruby-head
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-19mode
  - jruby-9.0.5.0
  - rbx-2
  - rbx-3.24
  - ruby-head
sudo: false
