addons:
  code_climate:
    repo_token: 8a344833c6693733b163f09a5243fa12dd7be0b69f0358b146c64dd4becabc60
before_script:
  - bin/brakeman
bundler_args: --clean --deployment --jobs=3 --retry=3 --without development production
cache: bundler
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-5.0.x
jdk:
  - openjdk8
language: ruby
matrix:
  include:
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-5.0.x 
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.rails-5.0.x 
    - rvm: rbx-2
      gemfile: gemfiles/Gemfile.rails-5.0.x 
  allow_failures:
    - rvm: 2.4.0-preview1
    - rvm: rbx-3.29
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: jruby-9.1.4.0
      gemfile: gemfiles/Gemfile.rails-5.0.x
rvm:
  #- 2.1
  #- 2.2.2
  #- 2.3.1
  #- 2.4.0-preview1
  - jruby-9.1.4.0
  #- rbx-2
  #- rbx-3.29
sudo: false
