addons:
  code_climate:
    repo_token: 8a344833c6693733b163f09a5243fa12dd7be0b69f0358b146c64dd4becabc60
before_script:
  - bin/brakeman
bundler_args: --clean --deployment --jobs=3 --retry=3 --without development production
sudo: false
cache: bundler
language: ruby
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - Gemfile
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-stable
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0-preview1
  - ruby-head
  - rbx-2
  - jruby-19mode
  - jruby-9
jdk:
  - openjdk7
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.3.0-preview1
  exclude:
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: 2.2
    - gemfile: gemfiles/Gemfile.rails-3.2.x
      rvm: ruby-head
